CREATE TABLE fiends (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  balance INTEGER DEFAULT 0,
  credit INTEGER DEFAULT 0,
  bankruptcies INTEGER DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);