CREATE TABLE wagers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId TEXT NOT NULL,
  betId INTEGER NOT NULL,
  amount INTEGER NOT NULL,
  isSettled BOOLEAN DEFAULT 0,
  choice TEXT NOT NULL,
  result TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES fiends(id),
  FOREIGN KEY (betId) REFERENCES bets(id)
);