CREATE TABLE bets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description TEXT NOT NULL,
  type TEXT NOT NULL,
  moneyLine INTEGER,
  spread REAL,
  isOpen BOOLEAN DEFAULT 1,
  isSettled BOOLEAN DEFAULT 0,
  result TEXT,
  date DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);