name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64
    
    steps:
      - name: Get short SHA
        id: sha
        run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Get GHCR repository
        id: repo
        run: |
          echo "image=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:${{ matrix.arch }}-${{ steps.sha.outputs.short }}
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:${{ matrix.arch }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  manifest:
    name: Create Multi-Arch Manifests
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Get short SHA
        id: sha
        run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Get GHCR repository
        id: repo
        run: |
          echo "image=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Create and push manifest for latest
        run: |
          docker manifest create ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:latest \
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:amd64-latest \
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:arm64-latest
          docker manifest push ${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:latest
      
      - name: Create and push manifest for SHA
        run: |
          docker manifest create "${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:${{ steps.sha.outputs.short }}" \
            "${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:amd64-${{ steps.sha.outputs.short }}" \
            "${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:arm64-${{ steps.sha.outputs.short }}"
          docker manifest push "${{ env.REGISTRY }}/${{ steps.repo.outputs.image }}:${{ steps.sha.outputs.short }}"