name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  typescript-build:
    name: TypeScript Build Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: TypeScript compile check
        run: yarn build